"use strict";

const winston = require('winston');
const Promise = require('bluebird');

/**
* Export functions for OpenAPISpec
*/
var SwaggerExporter = function () {
};


let generateSchema = function(json) {
  let schema = {};
  if( typeof json === 'object') {
    schema.type = 'object';
    schema.properties = {};
    Object.keys(json).forEach(property => {
      schema.properties[property] = generateSchema(json[property]);
    })
  }else {
    schema.type = typeof json;
  }
  return schema;
}

let convertNodeToPathItem = function(node, pathsObject) {
  const validMethods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch'];
  let pathItem = {};
  Object.keys(node.data).forEach( (key) => {
    if( validMethods.indexOf(key) < 0 ) {
      // this is not a valid key
      winston.log('warn', 'unable to convert response method ' + key + ' into OpenAPI Spec');
    }else {
      let responseData = {};
      let nodeResponseData = node.data[key];

      responseData.description = "auto generated by Rapido";
      responseData.produces = [nodeResponseData.response.contentType];
      responseData.consumes = [nodeResponseData.request.contentType];
      responseData.responses = {
        "200" : {
          "description": "auto generated by Rapido",
          "examples": {
          },
          "schema" : {
          }
        }
      };

      // Try to parse the string into a JSON object
      try {
        let jsonBody = JSON.parse(nodeResponseData.response.body);
        responseData.responses['200'].examples[nodeResponseData.response.contentType] =
          jsonBody;
        responseData.responses['200'].schema = generateSchema(jsonBody);
      }catch( e ) {
        if( e instanceof SyntaxError) {
          // This is not legal JSON, so treat it as a string
          responseData.responses['200'].examples['text/plain'] =
            nodeResponseData.response.body;
          responseData.responses['200'].schema = generateSchema(nodeResponseData.response.body);

        }
      }


      pathItem[key] = responseData;
    }
  });

  // Add this item to the paths object
  pathsObject[node.fullpath] = pathItem;

  // Process any children of this node recursively
  node.childNodes.forEach(child => {
    convertNodeToPathItem(child, pathsObject);
  })

  //return pathItem;
}

SwaggerExporter.prototype.exportTree = function(tree, title, description) {
  let swaggerDoc = {json: {}, yaml: ''};

  let info = {
    title: (title ? title : ''),
    description: description,
    version: 'rapido-sketch'
  };

  // Build path objects based on the tree structure
  let paths = {

  }

  tree.rootNodes.forEach( rootNode => {
    let pathInfo = convertNodeToPathItem(rootNode, paths);
    //paths[rootNode.fullpath] = pathInfo;
  })



  swaggerDoc.json = {
    swagger: "2.0",
    info: info,
    paths: paths
  }

  return swaggerDoc;
}

module.exports = SwaggerExporter;
