"use strict";

const winston = require('winston');
const Promise = require('bluebird');

/**
* Export functions for OpenAPISpec
*/
var SwaggerExporter = function () {
};


let generateSchema = function(json) {
  let schema = {};
  if( typeof json === 'object') {
    schema.type = 'object';
    schema.properties = {};
    Object.keys(json).forEach(property => {
      schema.properties[property] = generateSchema(json[property]);
    })
  }else {
    schema.type = typeof json;
  }
  return schema;
}

let objectToYaml = function(jsonObject, depth) {
  winston.log('debug', '[SwaggerExporter] objectToYaml called with: ', jsonObject);
  let yamlDoc = '';
  if( !depth ) {
    depth = 0;
  }

  Object.keys(jsonObject).forEach(key => {
    winston.log('debug', '[SwaggerExporter] objectToYaml processing key: ', key);
    let indent = '';
    for( let i = 0; i < depth; i++ ) {
      indent += '  ';
    }
    let jsonVal = jsonObject[key];
    if(typeof jsonVal === 'number') {
      yamlDoc += indent + key +  ': ' + jsonVal + '\n';
    }else if( typeof jsonVal === 'boolean') {
      yamlDoc += indent + key +  ': ' + jsonVal + '\n';
    }else if( typeof jsonVal === 'string') {
      yamlDoc += indent + key +  ': ""' + jsonVal + '""\n';
    }else if( typeof jsonVal === 'object' ) {
      if( Array.isArray(jsonVal)) {
        // Write the values as a hyphenated list
        yamlDoc += indent + key + ':\n';
        jsonVal.forEach(item => {
          yamlDoc += indent + '  - ' + item + '\n';
        })
      } else {
        yamlDoc += indent + key + ':\n';
        yamlDoc += objectToYaml( jsonVal, depth+1 );
      }
    }
  })
  return yamlDoc;
}

let convertNodeToPathItem = function(node, pathsObject) {
  winston.log('debug', '[SwaggerExporter] convertNodeToPathItem called for node: ', node);
  const validMethods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch'];
  let pathItem = {};
  Object.keys(node.data).forEach( (key) => {
    if( validMethods.indexOf(key) < 0 ) {
      // this is not a valid key
      winston.log('warn', 'unable to convert response method ' + key + ' into OpenAPI Spec');
    }else {
      let responseData = {};
      let nodeResponseData = node.data[key];

      responseData.description = "auto generated by Rapido";
      responseData.produces = [nodeResponseData.response.contentType];
      responseData.consumes = [nodeResponseData.request.contentType];
      responseData.responses = {
        "200" : {
          "description": "auto generated by Rapido",
          "examples": {
          },
          "schema" : {
          }
        }
      };

      // Try to parse the string into a JSON object
      try {
        let jsonBody = JSON.parse(nodeResponseData.response.body);
        responseData.responses['200'].examples[nodeResponseData.response.contentType] =
          jsonBody;
        responseData.responses['200'].schema = generateSchema(jsonBody);
      }catch( e ) {
        if( e instanceof SyntaxError) {
          // This is not legal JSON, so treat it as a string
          responseData.responses['200'].examples['text/plain'] =
            nodeResponseData.response.body;
          responseData.responses['200'].schema = generateSchema(nodeResponseData.response.body);

        }
      }
      pathItem[key] = responseData;
    }
  });

  // Add this item to the paths object
  pathsObject[node.fullpath] = pathItem;

  // Process any children of this node recursively
  if( node.children) {
    node.children.forEach(child => {
      convertNodeToPathItem(child, pathsObject);
    })
  }

  //return pathItem;
}

SwaggerExporter.prototype.exportTree = function(tree, title, description) {

  winston.log('debug', '[SwaggerExporter] exportTree called.');
  let swaggerDoc = {json: {}, yaml: ''};

  let info = {
    title: (title ? title : ''),
    description: description,
    version: 'rapido-sketch'
  };

  // Build path objects based on the tree structure
  let paths = {

  }

  winston.log('debug', '[SwaggerExporter] parsing root nodes');
  tree.rootNodes.forEach( rootNode => {
    winston.log('debug', '[SwaggerExporter] converting root: ', rootNode);
    let pathInfo = convertNodeToPathItem(rootNode, paths);
    //paths[rootNode.fullpath] = pathInfo;
  })

  winston.log('debug', '[SwaggerExporter] paths:', paths);


  swaggerDoc.json = {
    swagger: "2.0",
    info: info,
    paths: paths
  }

  winston.log('debug', '[SwaggerExporter] jsondoc:', swaggerDoc.json);

  swaggerDoc.yaml = objectToYaml(swaggerDoc.json);

  winston.log('debug', '[SwaggerExporter] returning swaggerdoc: ', swaggerDoc);

  return swaggerDoc;
}

module.exports = SwaggerExporter;
